language: node_js

node_js:
  - "stable"

env:
  global:
    - CC_TEST_REPORTER_ID=526777b6b3577c5b9bd1b18f565ce6fb5b49c07a7cfa89bb356dc2f05b34b326

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
branches:
  only:
    - develop

cache:
  directories:
    - "node_modules"

after_success:
  - npm run coverage

notifications:
  email: false