language: node_js

node_js:
  - "stable"

services:
  - postgresql

before_script:
  - psql -c 'create database "Quick-Credit-TEST";' -U postgres
  - npm run migration
script:
  - npm test

branches:
  only:
    - develop

cache:
  directories:
    - "node_modules"

after_success:
  - npm run coverage

notifications:
  email: false