language: node_js

node_js:
  - "stable"

script:
  - npm test

branches:
  only:
    - develop

cache:
  directories:
    - "node_modules"

after_success:
  - npm run coverage

notifications:
  email: false