const loans = [
  {
    id: 1,
    user: 'sneaky@gmail.com',
    createdOn: new Date(),
    status: 'pending',
    repaid: false,
    tenor: 4,
    amount: 1200.00,
    paymentInstallment: 315.00,
    balance: 1260.00,
    interest: 60.00,
  },
  {
    id: 2,
    user: 'rigatoni@gmail.com',
    createdOn: new Date(),
    status: 'approved',
    repaid: false,
    tenor: 5,
    amount: 1500.00,
    paymentInstallment: 315.00,
    balance: 1575.00,
    interest: 75.00,
  },
  {
    id: 3,
    user: 'sadio_mane@gmail.com',
    createdOn: new Date(),
    status: 'rejected',
    repaid: false,
    tenor: 8,
    amount: 2000.00,
    paymentInstallment: 262.50,
    balance: 1260,
    interest: 100.00,
  },
  {
    id: 4,
    user: 'pasta@gmail.com',
    createdOn: new Date(),
    status: 'approved',
    repaid: false,
    tenor: 5,
    amount: 1500.00,
    paymentInstallment: 315.00,
    balance: 1575.00,
    interest: 75.00,
  },
];
export default loans;
